### ISSUE TITLE
Permission denied when running Pulumi

### ISSUE THREAD

**Issue by juliobetta** [jaxxstorm/secure-cloud-access#1]
Hey @jaxxstorm, great [tutorial](https://www.leebriggs.co.uk/blog/2022/01/23/gha-cloud-credentials)!

I still have a problem though... I followed all the steps to create the Google Cloud credentials. It even returns the expected output for `gcloud auth list`. The problem is that when I run the pulumi step. It keeps saying that I don't have permission to perform an operation. (It works on my local machine)

```
docker:image:Image pulumi-playground-image  error: unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication
```

Here's my `deploy/infra/index.ts`

```ts
import * as pulumi from "@pulumi/pulumi";
import * as gcp from "@pulumi/gcp";
import * as google from "@pulumi/google-native";
import * as github from "@pulumi/github";

// get values from pulumi config
const config = new pulumi.Config("infra");
const stackName = pulumi.getStack();
const repository = config.require("repository");
const [, repoName] = repository.split("/");

// get values from pulumi config from the gcp namespace
// gcp config values are defined by the following pulumi command:
// pulumi config set gcp:<key> <value>
// ... or defined manually in the Pulumi.<stack>.yaml file
const projectID = gcp.config.project || "";

// Enable services

new gcp.projects.Service("EnableCloudRun", {
  project: projectID,
  service: "run.googleapis.com",
});

new gcp.projects.Service("EnableIAMCredentials", {
  project: projectID,
  service: "iamcredentials.googleapis.com",
});

new gcp.projects.Service("EnableContainer", {
  project: projectID,
  service: "containerregistry.googleapis.com",
});

// define GCP service account
const accountName = "github-actions-account"
const serviceAccount = new google.iam.v1.ServiceAccount(accountName, {
  accountId: accountName
});

[
  "roles/cloudasset.serviceAgent",
  "roles/run.developer",
  "roles/servicemanagement.quotaAdmin",
  "roles/containerregistry.ServiceAgent",
].forEach((role, index) => new gcp.projects.IAMMember(`github-actions-${index + 1}`, {
  project: projectID,
  role,
  member: pulumi.interpolate`serviceAccount:${serviceAccount.email}`
}));

const identityPool = new gcp.iam.WorkloadIdentityPool("github-actions", {
  disabled: false,
  workloadIdentityPoolId: `${accountName}-pool`,
});

const identityPoolProvider = new gcp.iam.WorkloadIdentityPoolProvider(
  "github-actions",
  {
    workloadIdentityPoolId: identityPool.workloadIdentityPoolId,
    workloadIdentityPoolProviderId: accountName,
    oidc: {
      issuerUri: "https://token.actions.githubusercontent.com",
    },
    attributeMapping: {
      "google.subject": "assertion.sub",
      "attribute.actor": "assertion.actor",
      "attribute.repository": "assertion.repository",
    },
  }
);

new gcp.serviceaccount.IAMMember("repository", {
  serviceAccountId: serviceAccount.name,
  role: "roles/iam.workloadIdentityUser",
  member: pulumi.interpolate`principalSet://iam.googleapis.com/${identityPool.name}/attribute.repository/${repository}`,
});

new github.ActionsSecret("identityProvider", {
  repository: repoName,
  secretName: `${stackName}_WORKLOAD_IDENTITY_PROVIDER`,
  plaintextValue: identityPoolProvider.name,
});

new github.ActionsSecret("subscriptionId", {
  repository: repoName,
  secretName: `${stackName}_SERVICE_ACCOUNT_EMAIL`,
  plaintextValue: serviceAccount.email,
});

export const workloadIdentityProviderUrl = identityPoolProvider.name;
export const serviceAccountEmail = serviceAccount.email;

```
`deploy/app/index.ts`

```ts
import * as pulumi from "@pulumi/pulumi";
import * as gcp from "@pulumi/gcp";
import * as docker from "@pulumi/docker";

const version = process.env.IMAGE_TAG || "dev-SNAPSHOT";

// get values from pulumi config
const config = new pulumi.Config("app");
const projectName = config.require("projectName");

// get values from pulumi config from the gcp namespace
// gcp config values are defined by the following pulumi command:
// pulumi config set gcp:<key> <value>
// ... or defined manually in the Pulumi.<stack>.yaml file
const location = gcp.config.region || "us-central1";
const projectID = gcp.config.project || "";

const enableCloudRun = new gcp.projects.Service("EnableCloudRun", {
  project: projectID,
  service: "run.googleapis.com",
});

// Clojure API ########

const appImage = new docker.Image(`${projectName}-image`, {
  imageName: pulumi.interpolate`gcr.io/${projectID}/yorba-resources:${version}`,
  build: {
    context: "../../",
  },
});

const appService = new gcp.cloudrun.Service(
  `${projectName}-service`,
  {
    location,
    project: projectID,
    template: {
      spec: {
        containers: [
          {
            image: appImage.imageName,
            resources: {
              limits: {
                memory: "1Gi",
              },
            },
          },
        ],
        containerConcurrency: 50,
      },
    },
  },
  { dependsOn: enableCloudRun }
);

// make the Cloud Run endpoint publicly accessible
const appResources = new gcp.cloudrun.IamMember(`${projectName}-everyone`, {
  service: appService.name,
  location,
  project: projectID,
  role: "roles/run.invoker",
  member: "allUsers",
});

// output the URL when the deployment is complete
export const yorbaResourcesUrl = appService.statuses[0].url;

```

... and my `deploy.yml`

```yaml
name: Deploy
on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    if: startsWith(${{ github.event.ref }}, 'refs/tags/v')
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Define Docker Image Tag
        run: |
          export TAG_REF=${{ github.event.ref }}
          export IMAGE_TAG=$(echo $TAG_REF | sed -e 's/refs\/tags\///g')
          echo "Docker Image Tag: ${IMAGE_TAG}"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Prepare Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install Clojure Tools
        uses: DeLaGuardo/setup-clojure@5.0
        with:
          cli: 1.11.1.1113
          lein: 2.9.8
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Tests
        run: clojure -M:test

      - id: auth
        name: Authenticate to GCP
        uses: google-github-actions/auth@v0
        with:
          create_credentials_file: true
          workload_identity_provider: ${{ secrets.DEV_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.DEV_SERVICE_ACCOUNT_EMAIL }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - id: gcloud
        name: gcloud auth
        run: |-
          gcloud info
          gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}" --project ${{ steps.auth.outputs.project_id }}
          gcloud auth list

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - run: cd deploy/app && npm install
        name: Install pulumi dependencies

      - run: lein deps
      - name: Generating JAR
        run: lein uberjar

      - name: Deploy to GCP
        uses: pulumi/actions@v3
        with:
          work-dir: deploy/app
          command: up
          stack-name: dev
          github-token: ${{ secrets.GITHUB_TOKEN }}
          upsert: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

```

**Comment by juliobetta** [comment]
I figured it out!

The first part was to include `"attribute.repository_owner": "assertion.repository_owner"` into the Workload's attribute mapping and change the repository member to 

```
member: pulumi.interpolate`principalSet://iam.googleapis.com/${identityPool.name}/attribute.repository_owner/${repoOwner}`,
```

>  refer to https://github.com/google-github-actions/auth/issues/77#issuecomment-990371420 to understand why we need to add `attribute.repository_owner` vs `attribute.repository`

The final piece was changing the authentication step and include a step to login to docker using the auth credentials.

```yaml
- id: auth
  name: Authenticate to GCP
  uses: google-github-actions/auth@v0
  with:
    token_format: 'access_token'
    access_token_lifetime: '300s'
    create_credentials_file: true
    workload_identity_provider: ${{ secrets.DEV_WORKLOAD_IDENTITY_PROVIDER }}
    service_account: ${{ secrets.DEV_SERVICE_ACCOUNT_EMAIL }}

- name: Set up Cloud SDK
  uses: google-github-actions/setup-gcloud@v0

  # This example uses the docker login action
- uses: 'docker/login-action@v1'
  with:
    registry: 'gcr.io' # or REGION-docker.pkg.dev
    username: 'oauth2accesstoken'
    password: '${{ steps.auth.outputs.access_token }}'
```

I hope this is useful for some lost soul wandering in the interwebs asking why permissions are soooo hard!
